### PR TITLE
A proposal to resolve check errors on CRAN when OA does not respond for some reason.

### PR DESCRIPTION
**Pull request by massimoaria**
A proposal to resolve check errors on CRAN when OA does not respond for some reason.

### CODE REVIEW

**Comment by massimoaria** [comment]
For the time being, the solution is implemented only in the oa_ngram function, but it could also be implemented in the other main functions: oa_fetch(), oa_snowball(), etc.

**Comment by massimoaria** [comment]
reprex::reprex({
  library(openalexR)
  
  #Here, an example with a valid id:
  oa_ngrams("https://openalex.org/W2755950973")
  
  #Here, an example when the function returns an error (in this case: id not valid)
  oa_ngrams("https://openalex.org/W27559509734")

})

**Comment by trangdata** [comment]
Hmm i feel like this is a pretty drastic change for the functions. What do you think @yjunechoe? I'll have time to investigate the CRAN email in detail later this week.

**Comment by yjunechoe** [comment]
I think I'd prefer the trycatch to be a bit more localized, but I also haven't dug into this yet so I can't say for sure. Is there a reprex for a failure that I can play around with?

**Comment by massimoaria** [comment]
There is a failed check a few days ago in our actions

**Pull request merged**
