### PR TITLE
Tracking coverage of OA entities

### PR DESCRIPTION
**Pull request by yjunechoe**
New file `openalexR-coverage.R` tracks `oa2df()`'s coverage of OA entity fields (currently just one draft for the Work entity)

New function `get_coverage()` introduces an interface to the coverage information, given an entity

This could also use some tests to ensure a match between what `oa2df()` actually returns vs. what we say it returns.

### CODE REVIEW

**Comment by yjunechoe** [comment]
@trangdata Could you help me double check my understanding of how we process variables from Work objects? And feel free to suggest anything to add to the `comments` column

**Comment by trangdata** [comment]
Thank you for putting this together @yjunechoe 💯 We needed this a long time ago. You're as thorough as always! 🚀  

I will make a PR if I think of other things to add to `comments`.

**Review by massimoaria — APPROVED** [review]

**Comment by rkrug** [comment]
I like this functionality. 

One point: in the case of e.g. biblio, where there are values extracted, it would be great if the field could be specified, e.g. `biblio.volume, volume` and also `biblio, NA` to indicate where the value is coming from and that biblio itself is removed.

That would make it clearer to understand and also make it possible to rename sub fields after extraction.

**Comment by rkrug** [comment]
Oh - I would also suggest to add the sorting of the fields in this function (or a separate function).

**Comment by trangdata** [comment]
@yjunechoe I can't add you as a reviewer because you opened the PR. But I would love to get your feedback when you have a minute.

- [ ] add warnings for the breaking changes
- [ ] add `keywords` as an entity, remove documentation for `concepts`
- [ ] add coverage for all entities, update test
- [ ] update readme and news

**Comment by trangdata** [comment]
Thank you @yjunechoe! So are you saying `oa2df_coverage <- get("oa2df_coverage", envir = asNamespace("openalexR"))` would work? Or it's still not working?

**Comment by trangdata** [comment]
@yjunechoe OK I have moved these points to #297 and #296. Let's continue our discussions there.

@rkrug Thanks for your input. I have added the warning in multiple places and described the changes in NEWS.md. We understand that breaking changes require adjustment, but they are often essential for keeping the package aligned with best practices and maximizing functionality over the long term.

**Pull request merged**
