### PR TITLE
Add apc information

### PR DESCRIPTION
**Pull request by yjunechoe**
The `apc_list` and `apc_paid` fields in a Work object are now returned as a single data frame in the `apc` column of the df output

```r
devtools::load_all()
x <- oa_fetch(identifier = c("W1964141474", "W1963991285"))
x$apc
#> [[1]]
#> [1] NA
#> 
#> [[2]]
#>   type value currency value_usd provenance
#> 1 list  4480      USD      4480       doaj
#> 2 paid  4480      USD      4480       doaj
```

### CODE REVIEW

**Comment by yjunechoe** [comment]
(I'm actually very puzzled by the testthat error I'm getting and can't seem to figure it out - will return to fix at a later time)

**Comment by trangdata** [comment]
> (I'm actually very puzzled by the testthat error I'm getting and can't seem to figure it out - will return to fix at a later time)

Very strange message indeed! We can always wait a couple days to see if this resolves itself on the OpenAlex's end.

**Review by trangdata — APPROVED** [review]
I had to modify some tests but it should be good now.

**Comment by yjunechoe** [comment]
Thanks for picking this back up for me!

**Pull request merged**
