### PR TITLE
More efficient abstract conversion

### PR DESCRIPTION
**Pull request by massimoaria**
A new, more efficient, and faster way to create abstracts from the abstract_inverted field

### CODE REVIEW

**Comment by trangdata** [comment]
Hi @massimoaria  I'm not sure I understand... Wouldn't this essentially eliminate a lot of the abstract?

**Comment by massimoaria** [comment]
No, it's just an alternative and more efficient way to covert inverted index abstract vectors to classical abstract string.
Results don't change.

**Comment by trangdata** [comment]
Hmm I must be missing something, because what I'm seeing is that only the first appearance of a word is kept with the new implementation. Could you elaborate @massimoaria?

```diff
- It is particularly suitable for science mapping at a time when the emphasis on empirical contributions is producing voluminous, fragmented, and controversial research streams.
+ It particularly suitable for science mapping at a time when the emphasis on empirical contributions producing voluminous, fragmented, and controversial research streams. 
- Science mapping is complex and unwieldly because it is multi-step and frequently requires numerous and diverse software tools, which are not all necessarily freeware. 
+ Science complex unwieldly because it multi-step frequently requires numerous diverse software tools, which are not necessarily freeware. 
- Although automated workflows that integrate these software tools into an organized data flow are emerging, in this paper we propose a unique open-source tool, designed by the authors, called bibliometrix, for performing comprehensive science mapping analysis.
+ Although automated workflows that integrate these tools into an organized data flow emerging, in this paper we propose unique open-source tool, designed by authors, called bibliometrix, performing comprehensive analysis.
- bibliometrix supports a recommended workflow to perform bibliometric analyses. 
+ bibliometrix supports recommended workflow perform bibliometric analyses.
- As it is programmed in R, the proposed tool is flexible and can be rapidly upgraded and integrated with other statistical R-packages. It is therefore useful in a constantly changing science such as bibliometrics.
+ As programmed R, proposed tool flexible can be rapidly upgraded integrated with other statistical R-packages. therefore useful constantly changing such as bibliometrics.
```

**Comment by massimoaria** [comment]
You are right. I made a mistake. Too stuffs to manage! Please remove the commit!
Thanks

**Pull request closed without merging**
